@startuml

!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Context.puml
!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Container.puml
!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Component.puml

title "DDD完整包结构"

Component(C_launcher, "启动器", "根据需要引入User Interface层的包，并提供启动类/配置文件")

Container_Boundary(C_ui, "user interface"){
    Component(C_ui_web, "ui-web", "WEB","主要是HTTP/REST接口")
    Component(C_ui_rpc_provider, "ui-provider", "RPC Sevice Provider","RPC服务提供层")
    Component(C_ui_worker, "ui-worker", "定时任务","Spring Task、分布式任务调度")
    Component(C_ui_listener, "ui-listener", "领域事件消费者","Kafka等消息队列监听器")
}

Component(C_application, "Application Service","应用服务层", "协调模型层和基础设施层完成业务操作")
Component(C_domain, "Domain","领域模型层", "领域模型包括实体、值对象、领域服务等，提供业务逻辑处理能力")
Container_Boundary(C_infrastructure, "Infrastructure","基础设施层", "基础设施层，向上提供各种支持"){
    Component(C_infrastructure_persistence, "infrastructure-persistence","基础设施-持久化", "实现Repository,封装数据模型ORM逻辑,向上层返回领域模型")
    Component(C_infrastructure_cache, "infrastructure-cache","基础设施-缓存", "为应用服务提供缓存服务")
    Component(C_infrastructure_gateway, "infrastructure-gateway","基础设施-外部调用网关", "外部调用的网关层，充当防腐层")
    Component(C_infrastructure_publisher, "infrastructure-publisher","基础设施-消息发布", "发送领域事件至消息中间件(如:kafka)")
}

Rel(C_launcher, C_ui_web, "打包")
Rel(C_launcher, C_ui_rpc_provider, "打包")
Rel(C_launcher, C_ui_worker, "打包")
Rel(C_launcher, C_ui_listener, "打包")



Rel(C_ui_web, C_application, "1.调用应用服务")
Rel(C_ui_rpc_provider, C_application, "1.调用应用服务")
Rel(C_ui_worker, C_application, "1.调用应用服务")
Rel(C_ui_listener, C_application, "1.调用应用服务")


Rel_R(C_application, C_domain, "2.调用领域模型完成业务逻辑")

Rel(C_application, C_infrastructure_persistence, "3.调用基础设施层的仓储服务完成领域模型加载、保存")
Rel(C_application, C_infrastructure_cache, "3.调用基础设施层完成缓存操作")
Rel(C_application, C_infrastructure_gateway, "3.调用外部服务")
Rel(C_application, C_infrastructure_publisher, "3.发布领域事件")

left to right direction

@enduml