@startuml

!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Context.puml
!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Container.puml
!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Component.puml

title "Service抽取业务逻辑之后的架构图"

Container_Boundary(CB_APP, "经典三层架构应用"){
    Component(C_Controller, "Controller","控制层", "接受请求")
    Component(C_Service, "Service", "服务层","协调各个组件完成用例")
    Component(C_Repostiry, "Repository", "仓储层","封装数据模型ORM的逻辑,保存或加载领域模型")
    Component(C_Model, "Model","业务模型", "业务逻辑处理")
}

ContainerDb(CDB, "Database", "数据库")

Rel(C_Controller, C_Service, "1.调用Service完成业务操作")
Rel_L(C_Service, C_Model, "2.业务逻辑处理")
Rel(C_Service, C_Repostiry, "3.数据持久化")

Rel(C_Repostiry, CDB, "读写","JDBC")

left to right direction

SHOW_LEGEND()

@enduml