@startuml

!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Context.puml
!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Container.puml
!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Component.puml

title "领域事件订阅者处理流程"

LAYOUT_LEFT_RIGHT()

System_Boundary(SB_SYS1, "限界上下文1"){
    Container_Ext(C_APP1, "DDD应用1","DDD架构应用")
}

ContainerQueue(MQ, "MQ", "消息中间件")

System_Boundary(SB_SYS2, "限界上下文2"){
    Container(C_APP2, "DDD应用2","DDD架构应用"){
        Component(C_UI, "UI-Subscriber","用户接口层-领域事件订阅者", "订阅消息中间件的领域事件消息")
        Component(C_Application, "Application","应用层", "协调基础设施与领域模型完成业务逻辑")
        Component(C_Domain, "Domain","领域层", "完成领域逻辑")
        Component(C_InfrastructureDb, "InfrastructureDb","数据库基础设施层", "提供基础设施支持")
    }
}

Rel(C_APP1, MQ, "a1.发布领域事件到消息中间件")

Rel_R(C_UI, MQ, "b1.监听消息中间件领域事件消息")
Rel(C_UI, C_Application, "b2.将领域消息转换成应用服务入参，调用应用服务")
Rel_L(C_Application, C_Domain, "a3.完成业务逻辑，并生成领域事件")
Rel(C_Application, C_InfrastructureDb, "b4.调用基础设施完成持久化领域模型和领域事件")

@enduml