@startuml

!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Context.puml
!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Container.puml
!include https://gitee.com/igingo/C4-PlantUML/raw/master/C4_Component.puml

title 经典三层架构示意图

Container_Boundary(CB_APP, "经典三层架构应用"){
    Component(C_Controller, "Controller","控制层", "接受用户请求")
    Component(C_Service, "Service", "服务层","处理业务逻辑")
    Component(C_Dao, "Dao", "数据访问层","封装数据库操作")
}

ContainerDb(CDB, "Database", "数据库")

Rel(C_Controller, C_Service, "处理业务逻辑")
Rel(C_Service, C_Dao, "数据持久化")
Rel(C_Dao, CDB, "读写","JDBC")
left to right direction

SHOW_LEGEND()

@enduml